{"name": "test_url_redirect_using_at_character[chromium0-https://pentest-ground.com:81//services]", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected not to be 'https://www.hackthissite.org/@hacker.com'\nActual value: https://www.hackthissite.org/@hacker.com \nCall log:\nPageAssertions.not_to_have_url with timeout 5000ms\n  - waiting for locator(\":root\")\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"", "trace": "self = <tests.client.url_redirection.TestForcedURLRedirect object at 0x104d09210>, page = <Page url='https://www.hackthissite.org/@hacker.com'>\ntarget_url = 'https://pentest-ground.com:81//services'\n\n    def test_url_redirect_using_at_character(self, page: Page, target_url):\n        with allure.step(\"Visit site and attempt forced-redirect using '@' character after redirection url\"):\n            forced_redirect_url = redirect_url+\"@hacker.com\"\n            page.goto(forced_redirect_url)\n>           expect(page).not_to_have_url(f\"{forced_redirect_url}\"), f\"Vulnerability found! Forced redirected to {redirect_url} was successful\"\nE           AssertionError: Page URL expected not to be 'https://www.hackthissite.org/@hacker.com'\nE           Actual value: https://www.hackthissite.org/@hacker.com \nE           Call log:\nE           PageAssertions.not_to_have_url with timeout 5000ms\nE             - waiting for locator(\":root\")\nE             -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\nE             -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\nE             -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\nE             -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\nE             -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\nE             -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\nE             -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\nE             -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\nE             -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\nE             -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\nE             -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\nE             -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\nE             -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\nE             -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\nE             -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\nE             -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\nE             -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\nE             -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n\nurl_redirection.py:122: AssertionError"}, "description": "Test for client-side URL redirection", "steps": [{"name": "Visit site and attempt forced-redirect using '@' character after redirection url", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected not to be 'https://www.hackthissite.org/@hacker.com'\nActual value: https://www.hackthissite.org/@hacker.com \nCall log:\nPageAssertions.not_to_have_url with timeout 5000ms\n  - waiting for locator(\":root\")\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n  -   locator resolved to <html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org…>…</html>\n  -   unexpected value \"https://www.hackthissite.org/@hacker.com\"\n\n", "trace": "  File \"/Users/pablovergara/Desktop/automation/vulcanite/tests/client/url_redirection.py\", line 122, in test_url_redirect_using_at_character\n    expect(page).not_to_have_url(f\"{forced_redirect_url}\"), f\"Vulnerability found! Forced redirected to {redirect_url} was successful\"\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 18245, in not_to_have_url\n    self._sync(\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playwright/_impl/_assertions.py\", line 131, in not_to_have_url\n    await self._not.to_have_url(urlOrRegExp, timeout)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playwright/_impl/_assertions.py\", line 120, in to_have_url\n    await self._expect_impl(\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/playwright/_impl/_assertions.py\", line 70, in _expect_impl\n    raise AssertionError(\n"}, "start": 1716688095501, "stop": 1716688101686}], "parameters": [{"name": "browser_name", "value": "'chromium'"}, {"name": "target_url", "value": "'https://pentest-ground.com:81//services'"}], "start": 1716688095501, "stop": 1716688101688, "uuid": "c65ec01b-fa53-4e9d-9c77-524411865846", "historyId": "563de65ca1ee179e4c6f160b0c5b2770", "testCaseId": "dfa9645afd77be11adf29dc4d8ff236d", "fullName": "tests.client.url_redirection.TestForcedURLRedirect#test_url_redirect_using_at_character", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "security"}, {"name": "parentSuite", "value": "tests.client"}, {"name": "suite", "value": "url_redirection"}, {"name": "subSuite", "value": "TestForcedURLRedirect"}, {"name": "host", "value": "Pablos-MBP"}, {"name": "thread", "value": "5647-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.client.url_redirection"}], "links": [{"type": "link", "url": "https://owasp.boireau.io/4-web_application_security_testing/11-client-side_testing/04-testing_for_client-side_url_redirect", "name": "Test for client-side URL redirection (WSTG-CLNT-04)"}]}